name: mask-recommender-inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.21.0
  - pandas>=1.3.0
  - arviz>=0.12.0
  - boto3>=1.26.0
  - requests>=2.28.0
  - pytest>=7.0.0
  - pip
  - pip:
    - pymc>=5.0.0

