name: mask_recommender_rf
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - joblib=1.4.2
  - boto3=1.34.162
  - requests=2.32.3
  - pytest=7.4.4
