name: mask_recommender
channels:
  - conda-forge
dependencies:
  - python
  - beautifulsoup4
  - clang
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - jupyter_contrib_nbextensions
  - pre_commit
  - blas
  - libopenblas
  - pytest
  - autopep8
  - opencv
  - openpyxl
  - protobuf
  - pymc
  - pip
  - pip:
    - "--editable=git+https://github.com/pymc-devs/pytensor.git"
    - mediapipe
    - levenshtein
  - selenium
  - tqdm

