name: Deploy Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 2: Deploy to staging (only on development branch pushes, not PRs)
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.9'
        bundler-cache: true

    - name: Deploy to Heroku Staging
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_STAGING_APP }}
      run: |
        # Install Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh

        # Login to Heroku
        echo $HEROKU_API_KEY | heroku auth:token --stdin

        # Deploy to staging
        git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:main

        # Run migrations
        heroku run rails db:migrate --app $HEROKU_APP

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Set up Python for Lambda deployment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        # Install Miniconda using a more reliable method
        curl -L -O "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        source $HOME/miniconda/bin/activate

        # Create environment from environment.yml
        conda env create -f python/mask_recommender/inference/environment.yml
        source activate mask-recommender-inference

    # Temporarily disabled due to ECR permissions issue
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and deploy training Lambda to staging
      id: build-training
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mask-recommender-training-staging
      run: |
        # Generate image tag
        IMAGE_TAG="development-$(date +%Y%m%d_%H%M%S)"

        echo ECR_REGISTRY: $ECR_REGISTRY
        echo ECR_REPOSITORY: $ECR_REPOSITORY
        echo IMAGE_TAG: $IMAGE_TAG

        # Build and push training Lambda
        cd python/mask_recommender/training
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        cd ../../..

        # Check if Lambda function exists
        if aws lambda get-function --function-name mask-recommender-training-staging 2>/dev/null; then
          echo "Function exists, updating..."
          aws lambda update-function-code \
            --function-name mask-recommender-training-staging \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
        else
          echo "Function does not exist, creating..."
          aws lambda create-function \
            --function-name mask-recommender-training-staging \
            --package-type Image \
            --code ImageUri=$ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --role arn:aws:iam::585068368316:role/lambda-execution-role \
            --timeout 900 \
            --memory-size 2048 \
            --environment "Variables={ENVIRONMENT=staging}"
        fi

        aws lambda wait function-updated \
          --function-name mask-recommender-training-staging

    - name: Ensure training Lambda config (staging)
      run: |
        set -euo pipefail
        FN="mask-recommender-training-staging"
        for i in 1 2 3; do
          if out=$(aws lambda update-function-configuration \
              --function-name "$FN" \
              --timeout 900 \
              --memory-size 3008 2>&1); then
            echo "Updated $FN configuration"
            exit 0
          fi
          if echo "$out" | grep -q 'ResourceConflictException'; then
            echo "Another update in progress for $FN. Retrying ($i/3)..."
            sleep 10
          else
            echo "$out"
            exit 1
          fi
        done
        echo "Timed out waiting to update $FN configuration"
        exit 1

    - name: Build and deploy inference Lambda to staging
      id: build-inference
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mask-recommender-inference-staging
      run: |
        # Generate image tag
        IMAGE_TAG="development-$(date +%Y%m%d_%H%M%S)"

        # Build and push inference Lambda
        cd python/mask_recommender/inference
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        cd ../../..

        # Check if Lambda function exists
        if aws lambda get-function --function-name mask-recommender-inference-staging 2>/dev/null; then
          echo "Function exists, updating..."
          aws lambda update-function-code \
            --function-name mask-recommender-inference-staging \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
        else
          echo "Function does not exist, creating..."
          aws lambda create-function \
            --function-name mask-recommender-inference-staging \
            --package-type Image \
            --code ImageUri=$ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --role arn:aws:iam::585068368316:role/lambda-execution-role \
            --timeout 300 \
            --memory-size 1024 \
            --environment "Variables={ENVIRONMENT=staging}"
        fi

        aws lambda wait function-updated \
          --function-name mask-recommender-inference-staging

    - name: Ensure inference Lambda config (staging)
      run: |
        set -euo pipefail
        FN="mask-recommender-inference-staging"
        for i in 1 2 3; do
          if out=$(aws lambda update-function-configuration \
              --function-name "$FN" \
              --timeout 900 \
              --memory-size 3008 2>&1); then
            echo "Updated $FN configuration"
            exit 0
          fi
          if echo "$out" | grep -q 'ResourceConflictException'; then
            echo "Another update in progress for $FN. Retrying ($i/3)..."
            sleep 10
          else
            echo "$out"
            exit 1
          fi
        done
        echo "Timed out waiting to update $FN configuration"
        exit 1

    - name: Send staging deployment success notification
      uses: dawidd6/action-send-mail@v3
      if: success()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Staging Deployment Successful - Development Branch"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Staging deployment completed successfully from development branch.

          Deployed components:
          - Heroku app: ${{ secrets.HEROKU_STAGING_APP }}
          - Lambda deployments: Temporarily disabled (ECR permissions issue)

          Database: Cloned from production
          Migrations: Applied successfully

    - name: Send staging deployment failure notification
      uses: dawidd6/action-send-mail@v3
      if: failure()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Staging Deployment Failed - Development Branch"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Staging deployment failed from development branch.

          Check the GitHub Actions logs for details.

  # Job 3: Deploy to production (only after successful staging deployment)
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.9'
        bundler-cache: true

    - name: Deploy to Heroku Production
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}
      run: |
        # Install Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh

        # Login to Heroku
        echo $HEROKU_API_KEY | heroku auth:token --stdin

        # Deploy to production
        git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:main

        # Run migrations
        heroku run rails db:migrate --app $HEROKU_APP

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Set up Python for Lambda deployment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        # Install Miniconda using a more reliable method
        curl -L -O "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        source $HOME/miniconda/bin/activate

        # Create environment from environment.yml
        conda env create -f python/mask_recommender/inference/environment.yml
        source activate mask-recommender-inference

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and deploy inference Lambda to production
      id: build-inference
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mask-recommender-inference-production
      run: |
        # Generate image tag
        IMAGE_TAG="development-$(date +%Y%m%d_%H%M%S)"

        # Build and push inference Lambda
        cd python/mask_recommender/inference
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        cd ../../..

        # Check if Lambda function exists
        if aws lambda get-function --function-name mask-recommender-inference-production 2>/dev/null; then
          echo "Function exists, updating..."
          aws lambda update-function-code \
            --function-name mask-recommender-inference-production \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
        else
          echo "Function does not exist, creating..."
          aws lambda create-function \
            --function-name mask-recommender-inference-production \
            --package-type Image \
            --code ImageUri=$ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --role arn:aws:iam::585068368316:role/lambda-execution-role \
            --timeout 300 \
            --memory-size 1024 \
            --environment "Variables={ENVIRONMENT=production}"
        fi

    - name: Build and deploy training Lambda to production
      id: build-training
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mask-recommender-training-production
      run: |
        # Generate image tag
        IMAGE_TAG="development-$(date +%Y%m%d_%H%M%S)"

        # Build and push training Lambda
        cd python/mask_recommender/training
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        cd ../../..

        # Check if Lambda function exists
        if aws lambda get-function --function-name mask-recommender-training-production 2>/dev/null; then
          echo "Function exists, updating..."
          aws lambda update-function-code \
            --function-name mask-recommender-training-production \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
        else
          echo "Function does not exist, creating..."
          aws lambda create-function \
            --function-name mask-recommender-training-production \
            --package-type Image \
            --code ImageUri=$ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --role arn:aws:iam::585068368316:role/lambda-execution-role \
            --timeout 900 \
            --memory-size 2048 \
            --environment "Variables={ENVIRONMENT=production}"
        fi

    - name: Ensure training Lambda config (production)
      continue-on-error: true
      run: |
        set -euo pipefail
        FN="mask-recommender-training-production"
        for i in 1 2 3; do
          if out=$(aws lambda update-function-configuration \
              --function-name "$FN" \
              --timeout 900 \
              --memory-size 3008 2>&1); then
            echo "Updated $FN configuration"
            exit 0
          fi
          if echo "$out" | grep -q 'ResourceConflictException'; then
            echo "Another update in progress for $FN. Retrying ($i/3)..."
            sleep 10
          else
            echo "$out"
            exit 1
          fi
        done
        echo "Timed out waiting to update $FN configuration"
        exit 1

    - name: Ensure inference Lambda config (production)
      run: |
        set -euo pipefail
        FN="mask-recommender-inference-production"
        for i in 1 2 3; do
          if out=$(aws lambda update-function-configuration \
              --function-name "$FN" \
              --timeout 900 \
              --memory-size 3008 2>&1); then
            echo "Updated $FN configuration"
            exit 0
          fi
          if echo "$out" | grep -q 'ResourceConflictException'; then
            echo "Another update in progress for $FN. Retrying ($i/3)..."
            sleep 10
          else
            echo "$out"
            exit 1
          fi
        done
        echo "Timed out waiting to update $FN configuration"
        exit 1

    - name: Send production deployment success notification
      uses: dawidd6/action-send-mail@v3
      if: success()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Production Deployment Successful - Development Branch"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Production deployment completed successfully from development branch.

          Deployed components:
          - Heroku app: ${{ secrets.HEROKU_PRODUCTION_APP }}
          - Inference Lambda: mask-recommender-inference-production
          - Training Lambda: mask-recommender-training-production

          Migrations: Applied successfully

    - name: Send production deployment failure notification
      uses: dawidd6/action-send-mail@v3
      if: failure()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Production Deployment Failed - Development Branch"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Production deployment failed from development branch.

          Check the GitHub Actions logs for details.
