name: Deploy PyTorch Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'python/mask_recommender/pytorch/**'
      - '.github/workflows/deploy-pytorch-lambda.yml'
    tags:
      - 'prod-*'
  workflow_dispatch:
    inputs:
      target_env:
        description: "Environment to deploy (staging|production)"
        required: false
        default: "staging"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: mask-recommender-pytorch

jobs:
  build-and-push:
    name: Build and push image to ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build-image
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPO: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          IMAGE_URI="$REGISTRY/$REPO:$IMAGE_TAG"
          LATEST_URI="$REGISTRY/$REPO:latest"

          # Ensure repository exists
          aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name "$REPO" >/dev/null

          # Build with context at python/mask_recommender
          docker build \
            -f python/mask_recommender/pytorch/Dockerfile \
            -t "$IMAGE_URI" \
            -t "$LATEST_URI" \
            python/mask_recommender

          docker push "$IMAGE_URI"
          docker push "$LATEST_URI"

          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
    outputs:
      image_uri: ${{ steps.build-image.outputs.image_uri }}

  deploy-staging:
    name: Deploy to staging
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_env == 'staging')
    permissions:
      contents: read
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || env.AWS_REGION }}

      - name: Update Lambda code (staging)
        env:
          FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_STAGING }}
          IMAGE_URI: ${{ needs.build-and-push.outputs.image_uri }}
        run: |
          set -euo pipefail
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --image-uri "$IMAGE_URI" \
            >/dev/null

      - name: Update Lambda environment (staging)
        env:
          FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_STAGING }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          set -euo pipefail
          # Fetch existing env vars and merge ENVIRONMENT/S3_BUCKET_REGION
          CFG=$(aws lambda get-function-configuration --function-name "$FUNCTION_NAME")
          ENV_VARS=$(echo "$CFG" | jq -r '.Environment.Variables // {}')
          MERGED=$(echo "$ENV_VARS" | jq '. + {ENVIRONMENT:"staging", S3_BUCKET_REGION: "'"$AWS_REGION"'"}')
          aws lambda update-function-configuration \
            --function-name "$FUNCTION_NAME" \
            --environment "Variables=$MERGED" \
            >/dev/null

  deploy-production:
    name: Deploy to production
    needs: build-and-push
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/prod-') || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_env == 'production')
    permissions:
      contents: read
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || env.AWS_REGION }}

      - name: Update Lambda code (production)
        env:
          FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_PRODUCTION }}
          IMAGE_URI: ${{ needs.build-and-push.outputs.image_uri }}
        run: |
          set -euo pipefail
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --image-uri "$IMAGE_URI" \
            >/dev/null

      - name: Update Lambda environment (production)
        env:
          FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_PRODUCTION }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          set -euo pipefail
          CFG=$(aws lambda get-function-configuration --function-name "$FUNCTION_NAME")
          ENV_VARS=$(echo "$CFG" | jq -r '.Environment.Variables // {}')
          MERGED=$(echo "$ENV_VARS" | jq '. + {ENVIRONMENT:"production", S3_BUCKET_REGION: "'"$AWS_REGION"'"}')
          aws lambda update-function-configuration \
            --function-name "$FUNCTION_NAME" \
            --environment "Variables=$MERGED" \
            >/dev/null
